(() => {
  if(location.protocol!=='http:')return;
  const $=id=>document.getElementById(id);
  const names={'sas-eurobonus':'SAS 유로보너스','asiana-club':'아시아나클럽',skyteam:'스카이팀 · 대한항공 마일리지','star-alliance':'스타얼라이언스 · 아시아나 마일리지'};
  const cabins={economy:'일반석','premium economy':'프리미엄 이코노미',business:'비즈니스',first:'일등석'};
  const messages={ACCESS_RESTRICTED:'항공사에서 접속을 제한했습니다. 확인하지 못한 날짜는 미조회로 남습니다.',LOGIN_REQUIRED:'조회용 Chrome에서 로그인해 주세요.',QUERY_MISMATCH:'선택한 조건과 항공사 결과가 달라 가져오지 않았습니다.',SEARCH_FAILED:'항공사 조회를 완료하지 못했습니다. 좌석 없음과는 다릅니다.',SEARCH_TIMEOUT:'항공사 응답을 기다리다 중단했습니다.',INVALID_QUERY:'공항과 월, 여정 조건을 확인해 주세요.',BUSY:'다른 조회가 진행 중입니다. 완료 후 다시 조회해 주세요.',REFERENCE_UNAVAILABLE:'기준 가는 편에 해당 등급이 없어 오는 편을 확인하지 못했습니다.',UNRECOGNIZED_RESULT:'항공사 결과를 해석하지 못했습니다. 좌석 없음으로 처리하지 않았습니다.',DATE_UNAVAILABLE:'항공사 달력에서 선택할 수 없는 날짜입니다.',DEPENDENCIES_MISSING:'Node.js와 npm ci 설치를 먼저 완료해 주세요.',BROWSER_ERROR:'조회용 Chrome 연결을 확인해 주세요.',FORM_REQUIRED:'공식 검색 화면 연결을 확인해야 합니다.',ROUTE_UNAVAILABLE:'항공사가 해당 노선의 공개 현황을 제공하지 않습니다.',ROUND_TRIP_REQUIRED:'대한항공 스카이팀은 왕복 조건으로 검색해야 합니다.'};
  let program=null,job=null,running=false,timer,polling=false,confirming=false;const selections=new Map();
  function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
  async function api(action,payload){const r=await fetch('/api/awards/'+action+(action==='status'?'?program='+encodeURIComponent(program):''),payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{});const d=await r.json();if(!r.ok)throw new Error(messages[d.error?.code]||'조회 서버 연결을 확인해 주세요.');return d;}
  function controls(){$('confirm-account-button').disabled=running||confirming;for(const e of $('award-form').querySelectorAll('input,select,button'))e.disabled=running||confirming;$('award-cancel').disabled=!running;$('open-account-button').disabled=running||confirming;$('award-cancel').hidden=!program;$('award-return-field').hidden=$('award-trip').value!=='ROUND_TRIP';$('award-trip').disabled=running||confirming||program==='skyteam';$('program').disabled=confirming;}
  function scope(){const round=$('award-trip').value==='ROUND_TRIP';$('award-return-field').hidden=!round;$('award-return-month').min=$('award-month').value;if($('award-return-month').value<$('award-month').value)$('award-return-month').value=$('award-month').value;$('award-scope').textContent=(round?'가는 편과 오는 편을 각각 조회합니다. 날짜별 좌석 표시가 왕복 조합의 예약을 보장하지는 않습니다.':'선택한 월 전체의 좌석을 조회합니다.')+(program==='asiana-club'?' 공식 월간 달력을 한 번에 가져옵니다. 공개 현황은 하루 한 번 갱신됩니다.':' 공식 날짜별 검색을 최대 6개씩 동시에 진행해 월별 달력으로 모읍니다. 월간 데이터를 한 번에 받는 방식은 아닙니다.');if(program==='skyteam')$('award-scope').textContent='스카이팀은 왕복 검색입니다. 가는 편은 오는 달 마지막 날을, 오는 편은 가는 달 첫 조회일의 첫 항공편을 기준으로 검색합니다. 모든 날짜 조합의 좌석을 보장하지 않습니다. 공식 날짜별 검색을 동시에 진행해 월별 달력으로 모읍니다. 월간 데이터를 한 번에 받는 방식은 아닙니다.';}
  function render(){
    const root=$('award-results');root.replaceChildren();if(!job)return;
    const requested=job.params.cabin;
    for(const leg of job.legs){
      const panel=node('article','','panel');panel.style.cssText='padding:24px;margin-bottom:24px';panel.append(node('h3',(leg.direction==='outbound'?'가는 편':'오는 편')+' · '+leg.origin+' → '+leg.destination+' · '+leg.month));
      if(leg.referenceDate)panel.append(node('p',(leg.direction==='outbound'?'오는 날 ':'가는 날 ')+leg.referenceDate+' 기준의 검색입니다. 오는 편은 기준일의 첫 번째 가는 항공편을 선택한 결과이며, 모든 왕복 조합을 확인한 것은 아닙니다.','program-hint'));
      const matched=leg.days.filter(d=>['available','partial'].includes(d.status)&&(requested==='all'||d.cabins.includes(requested)));
      const known=leg.days.filter(d=>['available','empty'].includes(d.status)).length;
      panel.append(node('p','좌석 표시 '+matched.length+'일 · 확인한 날짜 '+known+' / '+leg.days.length+'일','program-hint'));
      const grid=node('div','');grid.style.cssText='display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:10px;margin:20px 0';
      const details=node('div','');if(leg.days.some(d=>d.code==='REFERENCE_UNAVAILABLE'))panel.append(node('p','기준 가는 날에 선택할 항공편이 없어 오는 편을 확인하지 못한 날짜가 있습니다. 해당 날짜는 좌석 없음으로 처리하지 않았습니다.','program-hint'));if(leg.days.some(d=>d.status==='partial'))panel.append(node('p','일부 등급을 확인하지 못했습니다. 확인된 항공편은 표시하며, 나머지 등급의 좌석 유무는 알 수 없습니다.','program-hint'));
      for(const d of leg.days){const has=matched.includes(d),button=node('button',Number(d.date.slice(-2))+'일\n'+(has?(d.status==='partial'?'일부 등급 확인 · ':'')+d.cabins.filter(c=>requested==='all'||requested===c).map(c=>cabins[c]).join(' · '):d.status==='searching'?'조회 중':d.status==='failed'?'조회 실패':['available','empty'].includes(d.status)?'해당 등급 표시 없음':'미조회'));button.type='button';button.disabled=!has;button.style.cssText='white-space:pre-line;padding:18px 8px;border:1px solid '+(has?'#68b6bc':'#dce5ee')+';border-radius:12px;background:'+(has?'#effaf6':'#f8fafc')+';color:#183754;text-align:left';
        button.addEventListener('click',()=>{selections.set(program+leg.direction,d.date);details.replaceChildren(node('h4',d.date+' · '+leg.origin+' → '+leg.destination));if(d.sourceAt)details.append(node('p','항공사 공개 현황 기준: '+d.sourceAt,'program-hint'));details.append(node('p','가져온 시각: '+new Date(d.observedAt).toLocaleString('ko-KR'),'program-hint'));for(const f of d.flights.filter(f=>requested==='all'||f.cabin===requested)){details.append(node('p',[f.departureTime,f.flightNumber||f.operatedBy,f.referenceFlight?'기준 가는 편 '+f.referenceFlight:null,cabins[f.cabin],f.points?f.points.toLocaleString()+' 포인트':'필요 마일리지 미제공'].filter(Boolean).join(' · ')));}details.append(node('p','잔여 좌석 수와 최종 예약 가능 여부는 공식 사이트에서 확인해 주세요.','program-hint'));});grid.append(button);if(has&&selections.get(program+leg.direction)===d.date)button.click();}
      panel.append(grid,details);root.append(panel);
    }
  }
  async function poll(){if(!program||polling||confirming)return;polling=true;const target=program;clearTimeout(timer);try{const d=await api('status');if(target!==program)return;if(!job&&d.job){for(const [field,key] of [['origin','origin'],['destination','destination'],['month','month'],['return-month','returnMonth'],['trip','tripType'],['cabin','cabin']])if(d.job.params[key])$('award-'+field).value=d.job.params[key];scope();}job=d.job;running=job?.status==='running';const states={closed:'로그인·조회 창을 먼저 열어 주세요.',ready:'조회 창이 준비되었습니다.',login_required:'조회용 Chrome에서 로그인해 주세요.',restricted:'항공사 접속이 제한되었습니다.',searching:'로그인한 Chrome에서 날짜별 좌석을 조회하고 있습니다.',loading:'조회 창을 불러오는 중입니다.',form_required:'로그인 여부와 별개로 보너스 검색 화면 연결이 필요합니다. 로그인 완료·확인을 눌러 주세요.',action_required:'조회용 Chrome에서 보안 확인을 완료해 주세요.'};$('award-connection').textContent=(d.browser?.state==='ready'&&d.browser.authenticated?'로그인 확인 완료 · 검색 화면이 준비되었습니다.':states[d.browser?.state])||'조회 창 상태를 확인해 주세요.';if(job)$('award-progress').textContent=(job.status==='failed'?'이전 조회 · ':'')+'처리 '+job.completed+' / '+job.total+'일 · '+({running:'조회 중',complete:'조회 완료',partial:'일부 날짜 미확인',cancelled:'중단됨',failed:d.browser?.state==='ready'&&['LOGIN_REQUIRED','FORM_REQUIRED'].includes(job.code)?'현재 검색 화면이 준비되었습니다. 선택한 월 새로 조회를 눌러 주세요.':messages[job.code]||'조회 실패'})[job.status]+(job.startedAt?' · 소요 '+Math.max(0,Math.floor(((job.finishedAt?Date.parse(job.finishedAt):Date.now())-Date.parse(job.startedAt))/1000))+'초':'');controls();render();}catch(e){$('award-connection').textContent=e.message;}finally{polling=false;timer=setTimeout(poll,running?2000:5000);}}
  async function open(){try{$('award-connection').textContent='조회용 Chrome을 여는 중입니다.';await api('open',{program});await poll();}catch(e){$('award-connection').textContent=e.message;}}
  async function confirmLogin(target=program){
    if(confirming||running)return;
    confirming=true;controls();
    const label=target==='korean-air'?$('account-status'):$('award-connection');
    label.textContent='로그인 상태와 검색 화면을 확인하고 있습니다.';
    try{
      const r=await api('confirm-login',{program:target});
      const b=r.browser;
      const message=b?.state==='ready'?(b.authenticated?'로그인 확인 완료 · 검색 화면이 준비되었습니다.':target==='asiana-club'?'공개 좌석 검색 화면이 준비되었습니다. 로그인 없이 조회할 수 있습니다.':'검색 화면이 준비되었습니다. 로그인 상태는 실제 조회 시 추가 확인합니다.'):
        ({login_required:'조회용 Chrome에서 로그인을 완료한 뒤 다시 확인해 주세요.',form_required:'로그인 완료를 확인하지 못했습니다. 조회용 Chrome의 보너스 검색 화면을 확인해 주세요.',restricted:'항공사에서 접속을 제한했습니다.',action_required:'조회용 Chrome에서 보안 확인을 완료해 주세요.',closed:'로그인·조회 창을 먼저 열어 주세요.',loading:'검색 화면을 불러오고 있습니다. 잠시 후 다시 확인해 주세요.'})[b?.state]||'조회 창 연결을 확인하지 못했습니다.';
      $('account-status').textContent=message;
      label.textContent=message;
    }catch(e){label.textContent=e.message;}
    finally{confirming=false;controls();await poll();}
  }
  function activate(p){program=names[p]?p:null;job=null;running=false;render();$('award-progress').textContent='조회 전입니다.';clearTimeout(timer);controls();if(!program)return;$('award-title').textContent=names[p]+' · 월별 좌석 조회';$('award-note').textContent=p==='skyteam'?'대한항공과 스카이팀은 조회용 Chrome의 로그인 상태를 공유합니다. 스카이팀은 왕복 기준입니다.':'로그인은 각 사용자의 컴퓨터에 유지됩니다. 새 조회는 항공사에서 다시 검색하며 이전 데이터를 배포하지 않습니다.';if(p==='skyteam')$('award-trip').value='ROUND_TRIP';for(const o of $('award-cabin').options)o.disabled=(p!=='sas-eurobonus'&&o.value==='premium economy')||(p==='asiana-club'&&o.value==='first');if($('award-cabin').selectedOptions[0].disabled)$('award-cabin').value='all';scope();controls();void poll();}
  $('award-form').addEventListener('submit',async e=>{e.preventDefault();try{const params={program,origin:$('award-origin').value.trim().toUpperCase(),destination:$('award-destination').value.trim().toUpperCase(),month:$('award-month').value,returnMonth:$('award-return-month').value,tripType:$('award-trip').value,cabin:$('award-cabin').value};const r=await api('search',params);job=r.job;running=true;controls();render();await poll();}catch(e){$('award-progress').textContent=e.message;}});
  $('award-trip').addEventListener('change',scope);$('award-month').addEventListener('change',scope);$('award-cancel').addEventListener('click',async()=>{await api('cancel',{program});await poll();});
  const today=new Date(),last=new Date(Date.now()+359*86400000);for(let d=new Date(today.getFullYear(),today.getMonth(),1);d<=last;d.setMonth(d.getMonth()+1)){const value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');for(const id of ['award-month','award-return-month']){const o=node('option',d.getFullYear()+'년 '+(d.getMonth()+1)+'월');o.value=value;$(id).append(o);}}
  window.AwardLocal={activate,open,confirmLogin};activate($('program').value);
})();
